### PR TITLE
Make machine and uname settable from outside.

### PR DESCRIPTION
**Pull request by residuum**
Implements #8

### CODE REVIEW

**Comment by katjav** [comment]
Before pulling this in I have a few questions / remarks. Since any makefile variable can be overriden by:
- command line argument
- environment variables (with argument -e to make)

I guess you want to set 'machine' and 'uname' not via command line or environment, but from a parent makefile? If that is so, can we use the slightly simpler syntax like:

    ifndef machine
      machine := $(shell uname -m)
    endif

**Comment by residuum** [comment]
No, the idea is to be able to set machine and uname via command line, so that users can build all kinds of different platforms from the same system, e.g. using MXE to make Win32 builds on Linux with
`make machine=i386 uname=Windows`.

**Comment by katjav** [comment]
You can override make variables via command line. Try with 'make allvars' to see all variables, included those from environment and command line:

    make allvars machine=i386 uname=Windows

**Comment by residuum** [comment]
Then this PR is unnecessary.

**Comment by katjav** [comment]
I should add that 'uname=Windows' isn't an example that would work in practice. Makefile.pdlibbuilder can work with MinGW, where command uname returns a string containing 'MINGW'. If that string is found, 'system = Windows' is set.

    uname := $(shell uname)

    ...

    ifeq ($(findstring MINGW, $(uname)), MINGW)
      system = Windows
    endif

So you could use 'uname=MINGW' or 'system=Windows' to set the variables for cross compiling. There's one caveat: when Makefile.pdlibbuilder will ever be modified to support Cygwin too, the meaning of 'Windows' is no longer unambiguous. Then we may need to define 'system = MinGW' and system = Cygwin' instead, I don't know yet.

**Pull request closed without merging**
